### ISSUE TITLE
[Bug]: Livewire Entangle Error

### ISSUE THREAD

**Issue by alifdarsim** [joaopaulolndev/filament-edit-profile#10]
### What happened?

Livewire Entangle Error: Livewire property ['browserSessions'] cannot be found on component: ['joaopaulolndev.filament-edit-profile.pages.edit-profile-page']

livewire.js?id=07f22875:3889 Livewire Entangle Error: Livewire property ['deleteAccountData.deleteAccount'] cannot be found on component: ['joaopaulolndev.filament-edit-profile.pages.edit-profile-page']

### How to reproduce the bug

Open chrome console and see this error when using browser session and delete account

### Package Version

1.0.10

### PHP Version

8.2

### Laravel Version

11.9

**Comment by joaopaulolndev** [comment]
Please update to v1.0.11 and try again
