### ISSUE TITLE
[Bug]: Page reloads when you submit a form

### ISSUE THREAD

**Issue by ronssij** [joaopaulolndev/filament-edit-profile#11]
### What happened?

When you save changes from the profile information the page reloads and it shold should since form should be update without page reloading.

and adding `wire:submit.prevent` does not solve the issue.

### How to reproduce the bug

- Install the package
- Go to profile page
- Update name or email
- Click save

### Package Version

1.0

### PHP Version

8.3

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by joaopaulolndev** [comment]
Please update to v1.0.12 and test again.
Tks for the reported.

**Comment by ronssij** [comment]
@joaopaulolndev Would you agree if we copy the default behaviour of the filament's [EditProfile](https://github.com/filamentphp/filament/blob/43ab857c18f3f8fecd4a7ad0ab83c188e684f981/packages/panels/src/Pages/Auth/EditProfile.php#L188) class?

![image](https://github.com/joaopaulolndev/filament-edit-profile/assets/24932380/4ca4c09c-e468-40c6-ae76-09445cd5360e)

**Comment by joaopaulolndev** [comment]
Sure, you can open a new PR with this behavior to see
