### ISSUE TITLE
Request for new feature two factor authentication like in Jetstream.

### ISSUE THREAD

**Issue by mlselegant** [joaopaulolndev/filament-edit-profile#16]
### What happened?

I go through you package. Very nice.
But i just miss one feature i.e 2fa

### How to reproduce the bug

NA

### Package Version

2

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Windows

### Notes

NA

**Comment by joaopaulolndev** [comment]
It won't be a good idea to implement this function now because the V4 filament will come with this default behavior and this new version is about to be released.

https://github.com/filamentphp/filament/issues/12662
