### ISSUE TITLE
[Bug]: Erro ao atualizar v1.0.12 => v1.0.13

### ISSUE THREAD

**Issue by rodrigodeniel** [joaopaulolndev/filament-edit-profile#17]
### What happened?

Ao atualizar a versão x12 para x13, tive o erro abaixo ao abrir a pagina do profile

Property [$editProfileForm] not found on component: [joaopaulolndev.filament-edit-profile.pages.edit-profile-page]
o trecho do código com erro é:
`
        <?php echo e($this->editProfileForm); ?>
`
![image](https://github.com/joaopaulolndev/filament-edit-profile/assets/102530635/97dbd2eb-bc55-4cd7-bb9a-431c26dab39b)

### How to reproduce the bug

Atualizar versão de x12 para x13, abrir a pagina do profile

### Package Version

v1.0.13

### PHP Version

v8.2.16

### Laravel Version

v10.48.12

### Which operating systems does with happen with?

Linux

**Comment by joaopaulolndev** [comment]
Isso é o arquivo de cache.
Rode o comando php artisan optimize:clear e depois composer du
Veja se corrigiu e retorne aqui por favor

**Comment by rodrigodeniel** [comment]
olá, obrigado pelo retorno

executei os seguintes comandos, mas não obtive sucesso
php artisan cache:clear
php artisan config:clear
php artisan config:cache
php artisan route:clear
php artisan route:cache
php artisan view:clear
php artisan view:cache
php artisan event:clear
php artisan event:cache
php artisan optimize:clear
composer2 dump-autoload
composer2 clear-cache

**Comment by joaopaulolndev** [comment]
estranho isso, testei bastante aqui e parece bem.

Tenta isso:

composer remove joaopaulolndev/filament-world-clock

composer require joaopaulolndev/filament-world-clock

ou cria uma instalação nova de test para tentar ver se vai acontecer mesmo erro

**Comment by rodrigodeniel** [comment]
olá,
o composer remove (filament-edit-profile) não deu resultado, então iniciei um novo projeto, instalando tudo do zero. 
ai funcinou perfeitamente. 
obg

**Comment by rodrigodeniel** [comment]
Desculpe reabrir o tópico, mas acredito ter encontrado o problema
na versão anterior, eu publiquei a visualização: php artisan vendor:publish --tag="filament-edit-profile-views"
se atualizado a versão logo em seguida, ocorre o problema que mencionei acima. Caso eu elimine os arquivos (resources/views/vendor/filament-edit-profile) e crio novamente na nova versão, funciona perfeitamente.

**Comment by joaopaulolndev** [comment]
@rodrigodeniel , quando voce atualiza, voce tem que deletar os arquivos ja publicados e publicar novamente.
