### ISSUE TITLE
[Bug]: Class "App\Providers\Filament\FilamentEditProfilePlugin" not found

### ISSUE THREAD

**Issue by rxng** [joaopaulolndev/filament-edit-profile#20]
### What happened?

Following the instructions 

```
Add in AdminPanelProvider.php

->plugins([
    FilamentEditProfilePlugin::make()
])
```

this results in Class "App\Providers\Filament\FilamentEditProfilePlugin" not found

### How to reproduce the bug

added the plugin in AdminPanelProvider.php

### Package Version

1.0.14

### PHP Version

8.3.8

### Laravel Version

11.11

**Comment by joaopaulolndev** [comment]
You should use  the import

use Joaopaulolndev\FilamentEditProfile\FilamentEditProfilePlugin;
