### ISSUE TITLE
[Bug]: Visual of the browse sessions card

### ISSUE THREAD

**Issue by Grolicek** [joaopaulolndev/filament-edit-profile#23]
### What happened?

I think that the margins should be equal between all cards, becuase it doesn't look great if they cards are above each other with different starting margin...

### How to reproduce the bug

When you look at the margins at the top of different cards it seems messy to me...

![image](https://github.com/joaopaulolndev/filament-edit-profile/assets/58747066/7ee935c6-c4cf-41b4-9295-a6d11385ab09)

### Package Version

1.0.19

### PHP Version

8.2.0

### Laravel Version

11.11.0

### Which operating systems does with happen with?

Windows

**Comment by Grolicek** [comment]
If you'll agree with me, I think it should be easy to fix with removing highlighted text: https://github.com/joaopaulolndev/filament-edit-profile/blob/e7e37650f06929dbbb7fe6c904c2da9cb96853f5/resources/views/forms/components/browser-sessions.blade.php#L7C25-L7C29

**Comment by joaopaulolndev** [comment]
Hi @Grolicek , thanks for this help.
Already fixed, please update the package.
