### ISSUE TITLE
[Bug]: Validation Messages

### ISSUE THREAD

**Issue by fjarfs** [joaopaulolndev/filament-edit-profile#26]
### What happened?

![image](https://github.com/user-attachments/assets/e677c804-7ef6-407b-b796-b6534c4d314d)

how to custom validation messages?

### How to reproduce the bug

input wrong password

### Package Version

1.0

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by joaopaulolndev** [comment]
![image](https://github.com/user-attachments/assets/8ba83729-273d-4edf-aa18-1ee00743bf3a)

No replicated, maybe you should to publish in laravel your language

**Comment by fjarfs** [comment]
I have been publish by running
`php artisan vendor:publish --tag="filament-edit-profile-translations"`

and use id. All keys same with en.
![image](https://github.com/user-attachments/assets/1f78e96c-cf7b-40af-a8e3-de89841fc7fb)

I think the translations not from here
