### ISSUE TITLE
[Bug]: Error Delete Account

### ISSUE THREAD

**Issue by fjarfs** [joaopaulolndev/filament-edit-profile#27]
### What happened?

![image](https://github.com/user-attachments/assets/35ce8e22-451e-43bb-87dc-ae3b706c4033)

![image](https://github.com/user-attachments/assets/597511ab-d339-4ccf-a27d-9bf10a06f258)

I try to delete account, i insert incorrect password and get the error

### How to reproduce the bug

1. delete account
2. input incorrect password

### Package Version

1.0

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by joaopaulolndev** [comment]
Fixed in v1.0.22
Please update and try again
