### ISSUE TITLE
[Bug]: Avatar not displaying on Edit Profile page - showing white circle

### ISSUE THREAD

**Issue by YonkoSam** [joaopaulolndev/filament-edit-profile#29]
### What happened?

When navigating to the Edit Profile page, the avatar is not displayed correctly. Instead, a white circle is shown where the avatar should be.

### How to reproduce the bug

Log in to your account.
Upload an Avatar,
Navigate to the Edit Profile page.
Observe the avatar section.

### Package Version

1.0.22

### PHP Version

8.2.0

### Laravel Version

11.0.0

### Which operating systems does with happen with?

Windows

### Notes

![image](https://github.com/user-attachments/assets/e387c9a0-f472-4ade-aef9-3a543f1e265b)

**Comment by riyan** [comment]
i have same issue but in local environment running with `php artisan serve` default port is 8000, solving with changging `APP_URL=localhost` to `APP_URL=http://127.0.0.1:8000` in `.env` file and make sure storage folder can acessesed.
Dont know if this situation same with yours maybe this can be a referens for you.

**Comment by YonkoSam** [comment]
im using herd

**Comment by joaopaulolndev** [comment]
you need to change the variable in .env APP_URL=yourprojectname.test  
run php artisan storage:link
run php artisan optimize:clear

**Comment by YonkoSam** [comment]
yes it works thank you

**Comment by lucaruboni** [comment]
> i have same issue but in local environment running with `php artisan serve` default port is 8000, solving with changging `APP_URL=localhost` to `APP_URL=http://127.0.0.1:8000` in `.env` file and make sure storage folder can acessesed.
> Dont know if this situation same with yours maybe this can be a referens for you.

I have the Same problem as you but i can’t save my avatar , i’’ already with 127.0.0.1:8000 what can i do
