### ISSUE TITLE
[Bug]: Translator in custom field

### ISSUE THREAD

**Issue by riyan** [joaopaulolndev/filament-edit-profile#30]
### What happened?

Is it possible to use translator in custom field like this:
![image](https://github.com/user-attachments/assets/00435c92-67bc-4536-ba73-67a064fe1d2c)
if so, what is the correct way to use it

### How to reproduce the bug

try using translator in custom field and get this error
![image](https://github.com/user-attachments/assets/2fd7e25c-57a4-4c20-99bf-9a7c5655d597)

### Package Version

1.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by joaopaulolndev** [comment]
this variable gender does not exist inside the plugin translate file.
You should create inside your project and pass directly.
Ex: __('gender')

**Comment by riyan** [comment]
thank you it's work 👍👍👍
