### ISSUE TITLE
[Bug]: Can't create custom fields migration

### ISSUE THREAD

**Issue by cemkoker** [joaopaulolndev/filament-edit-profile#32]
### What happened?

Can't make migration for the custom fields

### How to reproduce the bug

When I try :
`php artisan vendor:publish --tag="filament-edit-profile-custom-field-migration"`

I see:
 `INFO  No publishable resources for tag [filament-edit-profile-custom-field-migration]`.

### Package Version

1.0.22

### PHP Version

8.3.9

### Laravel Version

11.16.0

### Which operating systems does with happen with?

macOS

**Comment by aiikendoit** [comment]
same problem

**Comment by ejjaquet** [comment]
In FilamentEditProfileServiceProvider.php on line 160, in the function 'migrationFileExists' we are checking on files with a .php extension, but that should be an extension of .php.stub. Tested and works after the change. I will create a PR.

**Comment by joaopaulolndev** [comment]
Fixed by @ejjaquet in v1.0.26.

Thanks a lot @ejjaquet !

**Comment by rizalahmaddd** [comment]
hello i want to ask.
in User model i have phone column how to show in edit profile bage below email? thanks
