### ISSUE TITLE
[Bug]: Route

### ISSUE THREAD

**Issue by nicola-morganti** [joaopaulolndev/filament-edit-profile#36]
### What happened?

Hi!

I can't see the edit profile on the left, even when I try to load it via the profile, I get: Route [filament.app.pages.edit-profile] not defined.

But the route is in the route list

The views are in vendor

I have also added it to the plugins

### How to reproduce the bug

.

### Package Version

newest

### PHP Version

8.2.12

### Laravel Version

newest

### Which operating systems does with happen with?

Windows

**Comment by ctoma** [comment]
Remember to clear your filament cache and it should work fine;
```
php artisan filament:clear-cached-components
```
Or on later versions of Filament
```
php artisan filament:optimize-clear
```
