### ISSUE TITLE
[Bug]: shouldShowSanctumTokens condition not work

### ISSUE THREAD

**Issue by wahyuief** [joaopaulolndev/filament-edit-profile#41]
### What happened?

I cannot filter visibility by user id

### How to reproduce the bug

Condition parameter on shouldShowSanctumTokens not work when using fn, callback doesn't work it still appears but it works if I use boolean

### Package Version

1.0.26

### PHP Version

8.2.22

### Laravel Version

11.21.0

### Which operating systems does with happen with?

Linux

**Comment by kidiatoliny** [comment]
@joaopaulolndev, we are unable to assign a branch to the issues.

@wahyuief, this issue has been resolved in version 1.0.27.

**Comment by joaopaulolndev** [comment]
@kidiatoliny  I don't know how can change this config.

And thank you so much for your help!

**Comment by wahyuief** [comment]
The callback work now, but I can't using condition like fn () => auth()->user()->id === 1. I think livewire running before auth middleware

**Comment by enrico-b-248** [comment]
I believe the regression is still in place.
It seems the condition is being checked during plugin boot/component registration, not when the authenticated user is rendering e.g. `/profile` page.

I cannot reopen the issue, I'd just like to have some feedback if others encountered this problem before opening a new one.

**Comment by jeffersongoncalves** [comment]
> I believe the regression is still in place.
> It seems the condition is being checked during plugin boot/component registration, not when the authenticated user is rendering e.g. `/profile` page.
> 
> I cannot reopen the issue, I'd just like to have some feedback if others encountered this problem before opening a new one.

please open a new thread with more details about the problem.
