### ISSUE TITLE
[Bug]: Property [$editProfileForm] not found on component: [joaopaulolndev.filament-edit-profile.pages.edit-profile-page]

### ISSUE THREAD

**Issue by MahmoudSlameh** [joaopaulolndev/filament-edit-profile#45]
### What happened?

Property [$editProfileForm] not found on component: [joaopaulolndev.filament-edit-profile.pages.edit-profile-page]

### How to reproduce the bug

Property [$editProfileForm] not found on component: [joaopaulolndev.filament-edit-profile.pages.edit-profile-page]

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by elmbrent118** [comment]
Got the same issue

**Comment by matthans0n** [comment]
You will need to execute the following command to republish the package views: ```php artisan vendor:publish --force --tag="filament-edit-profile-views"``` If you've made any manual changes to the views, you will need to make those changes to the newly published files.
