### ISSUE TITLE
[Bug]: json_decode(): Argument #1 ($json) must be of type string, array given when using custom fields

### ISSUE THREAD

**Issue by DivByZeroIT** [joaopaulolndev/filament-edit-profile#54]
### What happened?

After following the configuration to enable custom fields, if I go in the edit profile page I get a json_decode(): Argument #1 ($json) must be of type string, array given error.

this happens when in the user model custom_fields is (correctly) casted as array. If I remove the cast as array the edit profile page works.

### How to reproduce the bug

Just enable the cast as array of custom_fields in the user model

### Package Version

1.0.31

### PHP Version

8.2

### Laravel Version

11.x

### Which operating systems does with happen with?

macOS

**Comment by DivByZeroIT** [comment]
The error trace back to $this->form->fill(json_decode($data['custom_fields'], true) ?? []); in vendor/joaopaulolndev/filament-edit-profile/src/Livewire/CustomFieldsForm.php

**Comment by mkeremcansev** [comment]
@DivByZeroIT Hey, I solved this error in the following PR https://github.com/joaopaulolndev/filament-edit-profile/pull/55

**Comment by joaopaulolndev** [comment]
PR https://github.com/joaopaulolndev/filament-edit-profile/pull/55 
Merged to fix this issue

**Comment by DivByZeroIT** [comment]
Thanks Joao!!
