### ISSUE TITLE
[Bug]: `auth()->user()` is returning `null` in FilamentEditProfilePlugin

### ISSUE THREAD

**Issue by user3470** [joaopaulolndev/filament-edit-profile#56]
### What happened?

 I'm experiencing an issue where `auth()->user()` returns `null` in `FilamentEditProfilePlugin`. I’m trying to conditionally display certain features based on the authenticated user’s role, but it seems the session is unavailable in this specific plugin. However, `auth()->user()` works as expected in other plugins.

### How to reproduce the bug

Steps to Reproduce:

1. Set up `FilamentEditProfilePlugin` with the above configuration.
2. Attempt to access `auth()->user()` within the `shouldShowSanctumTokens()` callback .
3. Observe that `auth()->user()` returns `null` in `FilamentEditProfilePlugin.`

```php
// FilamentEditProfilePlugin setup (auth()->user() returns null here)
FilamentEditProfilePlugin::make()
    ->setNavigationLabel('My Profile')
    ->shouldShowSanctumTokens(
        fn() => dd(auth()->user()) // auth()->user() is null here
    );
```

### Package Version

1.0.32

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

Linux

### Notes

1. Is there a specific configuration or approach needed to ensure auth()->user() is accessible within `FilamentEditProfilePlugin`?
2. Could there be a timing issue with how Filament initializes plugins that affects session availability?

**Comment by ludndev** [comment]
Use `auth()->check()` instead.
