### ISSUE TITLE
[Bug]: Possibilidade de inserir o nome da coluna do avatar

### ISSUE THREAD

**Issue by FelipeSamuel** [joaopaulolndev/filament-edit-profile#57]
### What happened?

Estou tentando usar o plugin, mas ele utiliza o nome da coluna "avatar_url" e eu utilizo somente "avatar". Seria bacana passar um parametro indicando qual propriedade será armazenado.

### How to reproduce the bug

Estou tentando usar o plugin, mas ele utiliza o nome da coluna "avatar_url" e eu utilizo somente "avatar". Seria bacana passar um parametro indicando qual propriedade será armazenado.

### Package Version

2.0.0

### PHP Version

8.3.0

### Laravel Version

11.0.0

### Which operating systems does with happen with?

Linux

**Comment by ludndev** [comment]
I have the same issue. Many packages use "avatar" instead of "avatar_url". The solution would be to introduce field name in config, with "avatar_url" as default value. This will allow easy changes without breaking changes on updates.

**Comment by joaopaulolndev** [comment]
Merged @ludndev
