### ISSUE TITLE
[Question / Feature Request] Add the abilitiy to disable '->aside()' from forms

### ISSUE THREAD

**Issue by quasiperfect** [joaopaulolndev/filament-edit-profile#58]
### What happened?

hi

thanks for your package

is there a way to make disable the 'aside' ?
if not can you please make this customizable ? enabled by default but disable using a config value

thanks

### How to reproduce the bug

not a bug, i didn't find a way to ask a question

### Package Version

1.0

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by joaopaulolndev** [comment]
Hello @quasiperfect , for now, don't have this option.
