### ISSUE TITLE
[Bug]: Current password is not a field in my database table

### ISSUE THREAD

**Issue by guiireal** [joaopaulolndev/filament-edit-profile#9]
### What happened?

After install the module, i can update the current password, but i receive this error:

![image](https://github.com/joaopaulolndev/filament-edit-profile/assets/13739343/55cadcfd-8983-4f6c-8b52-4bd2d0b07535)

### How to reproduce the bug

Just follow the step-by-step of the project.

### Package Version

1.0.9

### PHP Version

8.3.7

### Laravel Version

11.9.1

### Which operating systems does with happen with?

Windows

**Comment by rmsramos** [comment]
Hi Guilherme, I was unable to reproduce your error, neither on a new installation nor on an old one.
What version of filament are you using?

**Comment by guiireal** [comment]
Hi everyone, thanks for the tips! I just updated the package to version `1.0.10` and it worked! Thank you!

![image](https://github.com/joaopaulolndev/filament-edit-profile/assets/13739343/50d29724-5de4-4b49-8ce5-1fe4f288adfe)


My `composer.json`

![image](https://github.com/joaopaulolndev/filament-edit-profile/assets/13739343/25459d59-3fe9-41ba-b8cd-dc2a20eaa073)
